### PR TITLE
Fix array comparison for Kraus operators

### PR DESCRIPTION
**Pull request by mattchan-tencent**
Fix from exact comparison to floating point equivalent comparison.

### CODE REVIEW

**Comment by nfwvogt** [comment]
Thank you @mattchan-tencent for your contribution!
This looks good and ready to merge!
Sorry for not mentioning this before in the repository, but to clarify the licensing situation we would like all contributors to pyquest_cffi to agree to a contributors license agreement.
If you are happy to agree to a CLA could you fill it out and send it to info@quantumsimulations.de?
If you don't feel comfortable doing this, we can treat this pull request as a bug report and solve the issue with a different code change.

**Comment by mattchan-tencent** [comment]
Ahh... No I don't think I can sign a CLA I'm sorry. There would probably be a ton of paperwork involved on my end.

Could you treat this as a bug report then please?

**Comment by nfwvogt** [comment]
Yeah, no worries, we will treat it as a bug report and fix it.

**Comment by nfwvogt** [comment]
Transferring to issue #29

**Pull request closed without merging**
